tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#444651",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#757682",
        "outline-variant": "#c5c5d3",
        "surface-tint": "#4059aa",
        "primary": "#00236f",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a8a",
        "on-primary-container": "#90a8ff",
        "inverse-primary": "#b6c4ff",
        "secondary": "#006d30",
        "on-secondary": "#ffffff",
        "secondary-container": "#92f5a4",
        "on-secondary-container": "#007233",
        "tertiary": "#002d48",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#004469",
        "on-tertiary-container": "#56b3f9",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#264191",
        "secondary-fixed": "#95f8a7",
        "secondary-fixed-dim": "#79db8d",
        "on-secondary-fixed": "#00210a",
        "on-secondary-fixed-variant": "#005323",
        "tertiary-fixed": "#cce5ff",
        "tertiary-fixed-dim": "#93ccff",
        "on-tertiary-fixed": "#001d31",
        "on-tertiary-fixed-variant": "#004b73",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "brand-blue-deep": "#1A00B0",
        "brand-blue-royal": "#1E3A8A",
        "brand-blue-vivid": "#2542B8",
        "brand-blue": "#1E3A8A",
        "brand-blue-soft": "#EFF6FF",
        "brand-blue-border": "#BFDBFE",
        "canvas-bg": "#F8FAFC",
        "surface-card": "#FFFFFF",
        "border-subtle": "#E2E8F0",
        "text-main": "#0F172A",
        "text-secondary": "#475569",
        "text-muted": "#94A3B8",
        "success-text": "#15803D",
        "success-deep": "#166534",
        "success-bg": "#DCFCE7",
        "success-border": "#BBF7D0",
        "warning-text": "#B45309",
        "warning-bg": "#FEF3C7",
        "warning-border": "#FDE68A",
        "critical-text": "#B91C1C",
        "critical-bg": "#FEE2E2",
        "critical-border": "#FECACA"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.5rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      }
    }
  }
};
